[target.aarch64-pc-windows-msvc]
linker = "C:\\Users\\hoops\\src\\anokye\\usb-bridge-abandoned\\tools\\link.exe"

[build]
rustflags = [
    "-C", "link-arg=/defaultlib:libvcruntime",
    "-C", "link-arg=/LIBPATH:C:\\Users\\hoops\\src\\anokye\\usb-bridge-abandoned\\tools\\crt",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\arm64",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\arm64",
]
